spring:
  application:
    name: chaeking
  profiles:
    active: local
  config:
    import:
      - chaeking.yml

  r2dbc:
    url: r2dbc:mariadb://localhost:3306/book
    username: test
    password: test
    pool:
      max-size: 50
      validation-query: SELECT 1
      initial-size: 10
      enabled: true

logging:
  level:
    org.springframework.r2dbc: DEBUG