spring:
  application:
    name: chaeking
  profiles:
    active: local
  config:
    import:
      - chaeking.yml
  datasource:
    url: jdbc:mariadb://localhost:3306/book
    driver-class-name: org.mariadb.jdbc.Driver
    username: test
    password: test
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      #      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-book
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: false
        hbm2ddl.auto: update
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        default_batch_fetch_size: 500
    open-in-view: false
    show-sql: true